import PyQt6.QtWidgets as qtw
from functools import partial
import csv

class MainWindow(qtw.QMainWindow):
    def __init__(self):
        super().__init__()
        self.central_widget = qtw.QWidget()
        
        self.layout = qtw.QStackedLayout()
        self.central_widget.setLayout(self.layout)

        self.setCentralWidget(self.central_widget)

        initialize(self)

def initialize(window):

    selection_page = qtw.QHBoxLayout()
    selection_widget = qtw.QWidget()
    selection_widget.setLayout(selection_page)
    selection_page.addStretch(1)
    selection_buttons = qtw.QVBoxLayout()
    selection_buttons.addStretch(5)
    student_button = qtw.QPushButton('Student login')    #selection page
    teacher_button = qtw.QPushButton('Teacher login')
    student_button.clicked.connect(lambda: student_login(window))
    teacher_button.clicked.connect(lambda: teacher_login(window))
    selection_buttons.addWidget(student_button)
    selection_buttons.addStretch(1)
    selection_buttons.addWidget(teacher_button)
    selection_buttons.addStretch(5)
    selection_page.addLayout(selection_buttons)
    selection_page.addStretch(1)
    window.layout.addWidget(selection_widget)
    window.layout.setCurrentIndex(0)

    login_page = qtw.QHBoxLayout()
    login_widget = qtw.QWidget()
    login_widget.setLayout(login_page)
    credentials_layout = qtw.QVBoxLayout()
    user_id_layout = qtw.QHBoxLayout()
    login_submit_layout = qtw.QHBoxLayout()
    password_layout = qtw.QHBoxLayout()
    return_home_layout = qtw.QVBoxLayout()
    return_home_button = qtw.QPushButton('<=')
    return_home_button.clicked.connect(lambda : homepage(window))
    return_home_layout.addWidget(return_home_button)
    return_home_layout.addStretch(1)
    user_id = qtw.QLineEdit()
    password = qtw.QLineEdit()
    showPassword = qtw.QCheckBox('Show Password')
    showPassword.toggled.connect(lambda checked: password.setEchoMode(qtw.QLineEdit.EchoMode.Normal if checked else qtw.QLineEdit.EchoMode.Password))
    window.login_error_text = qtw.QLabel('')
    password.setEchoMode(qtw.QLineEdit.EchoMode.Password)
    user_id.setMinimumWidth(250)
    password.setMinimumWidth(250)                              #login page
    user_id_layout.addStretch(1)
    user_id_layout.addWidget(qtw.QLabel('User ID: '))
    user_id_layout.addWidget(user_id)
    user_id_layout.addStretch(1)
    password_layout.addStretch(1)
    password_layout.addWidget(qtw.QLabel('Password:'))
    password_layout.addWidget(password)
    password_layout.addStretch(1)
    login_create_new_button = qtw.QPushButton('Create new user')
    login_submit_button = qtw.QPushButton('Submit')
    login_submit_button.clicked.connect(partial(login_submit, user_id, password, window))
    login_create_new_button.clicked.connect(partial(create_new_user, window))
    login_submit_layout.addStretch(4)
    login_submit_layout.addWidget(login_create_new_button)
    login_submit_layout.addStretch(1)
    login_submit_layout.addWidget(login_submit_button)
    login_submit_layout.addStretch(4)
    credentials_layout.addStretch(3)
    credentials_layout.addLayout(user_id_layout)
    credentials_layout.addStretch(1)
    credentials_layout.addLayout(password_layout)
    credentials_layout.addWidget(showPassword)
    credentials_layout.addWidget(window.login_error_text)
    credentials_layout.addStretch(2)
    credentials_layout.addLayout(login_submit_layout)
    credentials_layout.addStretch(4)
    login_page.addLayout(return_home_layout)
    login_page.addStretch(1)
    login_page.addLayout(credentials_layout)
    login_page.addStretch(1)
    window.layout.addWidget(login_widget)

    user_widget = qtw.QWidget()
    user_layout = qtw.QVBoxLayout()
    user_widget.setLayout(user_layout)
    user_return_layout = qtw.QHBoxLayout()
    text_box1_layout = qtw.QHBoxLayout()
    text_box2_layout = qtw.QHBoxLayout()
    text_box3_layout = qtw.QHBoxLayout()
    window.teacherCodeWidget = qtw.QWidget()
    teacher_code_layout = qtw.QHBoxLayout()
    window.teacherCodeWidget.setLayout(teacher_code_layout)
    window.userError = qtw.QLabel('')
    user_submit_layout = qtw.QHBoxLayout()
    window.userReturn = qtw.QPushButton('<=')
    window.userReturn.clicked.connect(lambda : None)
    user_return_layout.addWidget(window.userReturn)
    user_return_layout.addStretch(1)
    window.text1 = qtw.QLabel('')
    window.text2 = qtw.QLabel('')
    window.text3 = qtw.QLabel('')
    textBox1 = qtw.QLineEdit()
    textBox2 = qtw.QLineEdit()
    textBox3 = qtw.QLineEdit()
    textBox1.setMinimumWidth(200)
    textBox2.setMinimumWidth(200)
    textBox3.setMinimumWidth(200)
    text_box1_layout.addStretch(1)
    text_box2_layout.addStretch(1)
    text_box3_layout.addStretch(1)
    text_box1_layout.addWidget(window.text1)
    text_box2_layout.addWidget(window.text2)
    text_box3_layout.addWidget(window.text3)          #create new user and reset password
    text_box1_layout.addWidget(textBox1)
    text_box2_layout.addWidget(textBox2)
    text_box3_layout.addWidget(textBox3)
    text_box1_layout.addStretch(1)
    text_box2_layout.addStretch(1)
    text_box3_layout.addStretch(1)
    teacher_code_layout.addStretch(1)
    teacher_code_layout.addWidget(qtw.QLabel('Staff Code:'))
    teacherCode = qtw.QLineEdit()
    teacherCode.setMinimumWidth(200)
    teacher_code_layout.addWidget(teacherCode)
    teacher_code_layout.addStretch(1)
    user_submit_layout.addStretch(1)
    window.userSubmit = qtw.QPushButton('Submit')
    user_submit_layout.addWidget(window.userSubmit)
    user_submit_layout.addStretch(1)
    user_layout.addLayout(user_return_layout)
    user_layout.addStretch(2)
    user_layout.addLayout(text_box1_layout)
    user_layout.addStretch(1)
    user_layout.addLayout(text_box2_layout)
    user_layout.addStretch(1)
    user_layout.addLayout(text_box3_layout)
    user_layout.addStretch(1)
    user_layout.addWidget(window.teacherCodeWidget)
    user_layout.addStretch(2)
    user_layout.addLayout(user_submit_layout)
    user_layout.addStretch(4)
    window.layout.addWidget(user_widget)

    loggedInWidget = qtw.QWidget()
    loggedInLayout = qtw.QVBoxLayout()
    loggedInWidget.setLayout(loggedInLayout)
    helloLayout = qtw.QHBoxLayout()
    helloLayout.addStretch(1)
    window.hello = qtw.QLabel('')
    helloLayout.addWidget(window.hello)
    loggedTeacherLayout_ = qtw.QHBoxLayout()
    window.loggedTeacher = qtw.QWidget()
    loggedTeacherLayout = qtw.QHBoxLayout()
    window.loggedTeacher.setLayout(loggedTeacherLayout)
    loggedInLayout1 = qtw.QHBoxLayout()
    loggedInLayout2 = qtw.QHBoxLayout()
    loggedInLayout3 = qtw.QHBoxLayout()
    loggedInLayout4 = qtw.QHBoxLayout()
    loggedTeacherLayout_.addStretch(1)
    loggedTeacherLayout_.addWidget(window.loggedTeacher)
    loggedTeacherLayout_.addStretch(1)
    loggedTeacherLayout.addStretch(1)
    makeTestButton = qtw.QPushButton('Make Test')
    loggedTeacherLayout.addWidget(makeTestButton)
    loggedTeacherLayout.addStretch(1)
    loggedInLayout1.addStretch(1)
    window.existingTest = qtw.QComboBox()
    loggedInLayout1.addWidget(window.existingTest)
    loggedInLayout1.addStretch(1)
    loggedInLayout2.addStretch(1)
    viewResults = qtw.QPushButton('View Results')
    loggedInLayout2.addWidget(viewResults)
    loggedInLayout2.addStretch(1)
    loggedInLayout3.addStretch(1)
    changePassword = qtw.QPushButton('Change Password')
    loggedInLayout3.addWidget(changePassword)
    loggedInLayout3.addStretch(1)
    loggedInLayout4.addStretch(1)
    logout = qtw.QPushButton('Logout')
    logout.clicked.connect(partial(homepage, window))
    loggedInLayout4.addWidget(logout)
    loggedInLayout4.addStretch(1)
    loggedInLayout.addStretch(1)
    loggedInLayout.addLayout(helloLayout)
    loggedInLayout.addStretch(3)
    loggedInLayout.addLayout(loggedTeacherLayout_)
    loggedInLayout.addLayout(loggedInLayout1)
    loggedInLayout.addStretch(1)
    loggedInLayout.addLayout(loggedInLayout2)
    loggedInLayout.addStretch(1)
    loggedInLayout.addLayout(loggedInLayout3)
    loggedInLayout.addStretch(2)
    loggedInLayout.addLayout(loggedInLayout4)
    loggedInLayout.addStretch(5)
    window.layout.addWidget(loggedInWidget)

homepage = lambda window : window.layout.setCurrentIndex(0)

def student_login(window):
    window.login_error_text.hide()
    window.currentMode = False
    window.layout.setCurrentIndex(1)

def teacher_login(window):
    window.login_error_text.hide()
    window.currentMode = True
    window.layout.setCurrentIndex(1)

def refresh():
    credentials.append({'Developer' : 'password'})
    credentials.append({'Developer' : 'password'})
    topics.append('Stars and Galaxies')
    topics.append('topic 2')

def login_submit(user_id_obj, password_obj, window):
    user_id = user_id_obj.text()
    password = password_obj.text()
    if user_id in credentials[window.currentMode]:
        if password == credentials[window.currentMode][user_id]:
            user_id_obj.setText('')
            password_obj.setText('')
            window.userID = user_id
            window.password = password
            loggedInPage(window)
        else:
            password_obj.setText('')
            window.login_error_text.setText('Invalid Password')
            window.login_error_text.show()
    else:
        user_id_obj.setText('')
        password_obj.setText('')
        window.login_error_text.setText('Invalid user ID')
        window.login_error_text.show()

def create_new_user(window):
    window.userReturn.clicked.disconnect()
    if window.currentMode:
        window.teacherCodeWidget.show()
        window.userReturn.clicked.connect(partial(teacher_login, window))
    else:
        window.teacherCodeWidget.hide()
        window.userReturn.clicked.connect(partial(student_login, window))
    window.text1.setText('Enter Username:  ')
    window.text2.setText('Enter Password:  ')
    window.text3.setText('Confirm Password:')
    window.layout.setCurrentIndex(2)

def loggedInPage(window):
    window.hello.setText('Hello ' + window.userID + '!')
    window.existingTest.addItems(topics)
    if window.currentMode:
        window.loggedTeacher.show()
        window.existingTest.setCurrentText('Alter test')
    else:
        window.loggedTeacher.hide()
        window.existingTest.setCurrentText('Take test')
    window.layout.setCurrentIndex(3)

credentials = list()
topics = list()
refresh()
app = qtw.QApplication([])
window = MainWindow()
window.show()
app.exec()
