import PyQt6.QtWidgets as qtw
from functools import partial
import csv

class MainWindow(qtw.QMainWindow):
    def __init__(self):
        super().__init__()
        self.central_widget = qtw.QWidget()
        
        self.layout = qtw.QStackedLayout()
        self.central_widget.setLayout(self.layout)

        self.setCentralWidget(self.central_widget)

        initialize(self)

def initialize(window):

    selection_page = qtw.QHBoxLayout()
    selection_widget = qtw.QWidget()
    selection_widget.setLayout(selection_page)
    selection_page.addStretch(1)
    selection_buttons = qtw.QVBoxLayout()
    selection_buttons.addStretch(5)
    student_button = qtw.QPushButton('Student login')    #selection page
    teacher_button = qtw.QPushButton('Teacher login')
    student_button.clicked.connect(lambda: student_login(window))
    teacher_button.clicked.connect(lambda: teacher_login(window))
    selection_buttons.addWidget(student_button)
    selection_buttons.addStretch(1)
    selection_buttons.addWidget(teacher_button)
    selection_buttons.addStretch(5)
    selection_page.addLayout(selection_buttons)
    selection_page.addStretch(1)
    window.layout.addWidget(selection_widget)
    window.layout.setCurrentIndex(0)

    login_page = qtw.QHBoxLayout()
    login_widget = qtw.QWidget()
    login_widget.setLayout(login_page)
    credentials_layout = qtw.QVBoxLayout()
    user_id_layout = qtw.QHBoxLayout()
    login_submit_layout = qtw.QHBoxLayout()
    password_layout = qtw.QHBoxLayout()
    return_home_layout = qtw.QVBoxLayout()
    return_home_button = qtw.QPushButton('<=')
    return_home_button.clicked.connect(lambda : homepage(window))
    return_home_layout.addWidget(return_home_button)
    return_home_layout.addStretch(1)
    user_id = qtw.QLineEdit()
    password = qtw.QLineEdit()
    showPassword = qtw.QCheckBox('Show Password')
    showPassword.toggled.connect(lambda checked: password.setEchoMode(qtw.QLineEdit.EchoMode.Normal if checked else qtw.QLineEdit.EchoMode.Password))
    window.login_error_text = qtw.QLabel('')
    password.setEchoMode(qtw.QLineEdit.EchoMode.Password)
    user_id.setMinimumWidth(250)
    password.setMinimumWidth(250)                              #login page
    user_id_layout.addStretch(1)
    user_id_layout.addWidget(qtw.QLabel('User ID: '))
    user_id_layout.addWidget(user_id)
    user_id.returnPressed.connect(password.setFocus)
    user_id_layout.addStretch(1)
    password_layout.addStretch(1)
    password_layout.addWidget(qtw.QLabel('Password:'))
    password_layout.addWidget(password)
    password.returnPressed.connect(partial(login_submit, user_id, password, window))
    password_layout.addStretch(1)
    login_create_new_button = qtw.QPushButton('Create new user')
    login_submit_button = qtw.QPushButton('Submit')
    login_submit_button.clicked.connect(partial(login_submit, user_id, password, window))
    login_create_new_button.clicked.connect(partial(create_new_user, window))
    login_submit_layout.addStretch(4)
    login_submit_layout.addWidget(login_create_new_button)
    login_submit_layout.addStretch(1)
    login_submit_layout.addWidget(login_submit_button)
    login_submit_layout.addStretch(4)
    credentials_layout.addStretch(3)
    credentials_layout.addLayout(user_id_layout)
    credentials_layout.addStretch(1)
    credentials_layout.addLayout(password_layout)
    credentials_layout.addWidget(showPassword)
    credentials_layout.addWidget(window.login_error_text)
    credentials_layout.addStretch(2)
    credentials_layout.addLayout(login_submit_layout)
    credentials_layout.addStretch(4)
    login_page.addLayout(return_home_layout)
    login_page.addStretch(1)
    login_page.addLayout(credentials_layout)
    login_page.addStretch(1)
    window.layout.addWidget(login_widget)

    user_widget = qtw.QWidget()
    user_layout = qtw.QVBoxLayout()
    user_widget.setLayout(user_layout)
    user_return_layout = qtw.QHBoxLayout()
    text_box1_layout = qtw.QHBoxLayout()
    text_box2_layout = qtw.QHBoxLayout()
    text_box3_layout = qtw.QHBoxLayout()
    window.teacherCodeWidget = qtw.QWidget()
    teacher_code_layout = qtw.QHBoxLayout()
    window.teacherCodeWidget.setLayout(teacher_code_layout)
    window.userError = qtw.QLabel('')
    user_submit_layout = qtw.QHBoxLayout()
    window.userReturn = qtw.QPushButton('<=')
    window.userReturn.clicked.connect(lambda : None)
    user_return_layout.addWidget(window.userReturn)
    user_return_layout.addStretch(1)
    window.text1 = qtw.QLabel('')
    window.text2 = qtw.QLabel('')
    window.text3 = qtw.QLabel('')
    textBox1 = qtw.QLineEdit()
    textBox2 = qtw.QLineEdit()
    textBox3 = qtw.QLineEdit()
    textBox1.setMinimumWidth(200)
    textBox2.setMinimumWidth(200)
    textBox3.setMinimumWidth(200)
    text_box1_layout.addStretch(1)
    text_box2_layout.addStretch(1)
    text_box3_layout.addStretch(1)
    text_box1_layout.addWidget(window.text1)
    text_box2_layout.addWidget(window.text2)
    text_box3_layout.addWidget(window.text3)          #create new user and reset password
    text_box1_layout.addWidget(textBox1)
    text_box2_layout.addWidget(textBox2)
    text_box3_layout.addWidget(textBox3)
    text_box1_layout.addStretch(1)
    text_box2_layout.addStretch(1)
    text_box3_layout.addStretch(1)
    teacher_code_layout.addStretch(1)
    teacher_code_layout.addWidget(qtw.QLabel('Staff Code:'))
    teacherCode = qtw.QLineEdit()
    teacherCode.setMinimumWidth(200)
    teacher_code_layout.addWidget(teacherCode)
    teacher_code_layout.addStretch(1)
    user_submit_layout.addStretch(1)
    window.userSubmit = qtw.QPushButton('Submit')
    user_submit_layout.addWidget(window.userSubmit)
    user_submit_layout.addStretch(1)
    user_layout.addLayout(user_return_layout)
    user_layout.addStretch(2)
    user_layout.addLayout(text_box1_layout)
    user_layout.addStretch(1)
    user_layout.addLayout(text_box2_layout)
    user_layout.addStretch(1)
    user_layout.addLayout(text_box3_layout)
    user_layout.addStretch(1)
    user_layout.addWidget(window.teacherCodeWidget)
    user_layout.addStretch(2)
    user_layout.addLayout(user_submit_layout)
    user_layout.addStretch(4)
    window.layout.addWidget(user_widget)

    loggedInWidget = qtw.QWidget()
    loggedInLayout = qtw.QVBoxLayout()
    loggedInWidget.setLayout(loggedInLayout)
    helloLayout = qtw.QHBoxLayout()
    helloLayout.addStretch(1)
    window.hello = qtw.QLabel('')
    helloLayout.addWidget(window.hello)
    loggedTeacherLayout_ = qtw.QHBoxLayout()
    window.loggedTeacher = qtw.QWidget()
    loggedTeacherLayout = qtw.QHBoxLayout()
    window.loggedTeacher.setLayout(loggedTeacherLayout)
    loggedInLayout1 = qtw.QHBoxLayout()
    loggedInLayout2 = qtw.QHBoxLayout()
    loggedInLayout3 = qtw.QHBoxLayout()
    loggedInLayout4 = qtw.QHBoxLayout()
    loggedTeacherLayout_.addStretch(1)
    loggedTeacherLayout_.addWidget(window.loggedTeacher)
    loggedTeacherLayout_.addStretch(1)
    loggedTeacherLayout.addStretch(1)
    makeTestButton = qtw.QPushButton('Make Test')
    makeTestButton.clicked.connect(partial(makeTest, window))
    loggedTeacherLayout.addWidget(makeTestButton)
    loggedTeacherLayout.addStretch(1)
    loggedInLayout1.addStretch(1)
    window.testLabel = qtw.QLabel('')
    window.existingTest = qtw.QComboBox()
    testSubmit = qtw.QPushButton('Confirm test')
    loggedInLayout1.addWidget(window.testLabel)
    loggedInLayout1.addWidget(window.existingTest)
    loggedInLayout1.addWidget(testSubmit)
    loggedInLayout1.addStretch(1)
    loggedInLayout2.addStretch(1)
    viewResults = qtw.QPushButton('View Results')
    loggedInLayout2.addWidget(viewResults)
    loggedInLayout2.addStretch(1)
    loggedInLayout3.addStretch(1)
    changePassword = qtw.QPushButton('Change Password')
    loggedInLayout3.addWidget(changePassword)
    loggedInLayout3.addStretch(1)
    loggedInLayout4.addStretch(1)
    logout = qtw.QPushButton('Logout')
    logout.clicked.connect(partial(homepage, window))
    loggedInLayout4.addWidget(logout)
    loggedInLayout4.addStretch(1)
    loggedInLayout.addStretch(1)
    loggedInLayout.addLayout(helloLayout)
    loggedInLayout.addStretch(3)
    loggedInLayout.addLayout(loggedTeacherLayout_)
    loggedInLayout.addLayout(loggedInLayout1)
    loggedInLayout.addStretch(1)
    loggedInLayout.addLayout(loggedInLayout2)
    loggedInLayout.addStretch(1)
    loggedInLayout.addLayout(loggedInLayout3)
    loggedInLayout.addStretch(2)
    loggedInLayout.addLayout(loggedInLayout4)
    loggedInLayout.addStretch(5)
    window.layout.addWidget(loggedInWidget)

    testWidget = qtw.QWidget()
    testLayout = qtw.QHBoxLayout()
    testWidget.setLayout(testLayout)
    questionNumberLayout = qtw.QVBoxLayout()
    window.questionNumbers = list()
    questionNumberLayout.addStretch(3)
    for i in range(10):
        window.questionNumbers.append(qtw.QPushButton(f'{i + 1}'))
        questionNumberLayout.addWidget(window.questionNumbers[i])
    questionNumberLayout.addStretch(7)
    testLayout.addLayout(questionNumberLayout)
    _testContent_ = qtw.QHBoxLayout()
    testContent_ = qtw.QVBoxLayout()
    testContent = qtw.QVBoxLayout()
    testSubmitLayout = qtw.QHBoxLayout()
    testSubmitLayout.addStretch(4)
    testSubmit = qtw.QPushButton('Submit')
    testSubmitLayout.addWidget(testSubmit)
    testSubmitLayout.addStretch(1)
    testContent.addStretch(2)
    testContent.addLayout(testSubmitLayout)
    window.questionLayout = qtw.QStackedLayout()
    window.questions = list()
    for i in range(10):
        tempWidget = qtw.QWidget()
        tempLayout = qtw.QHBoxLayout()
        tempLayout.addWidget(qtw.QLabel(f'{i + 1})'))
        window.questions.append(qtw.QTextEdit())
        window.questions[i].setMinimumWidth(500)
        tempLayout.addWidget(window.questions[i])
        tempLayout.addStretch(1)
        tempWidget.setLayout(tempLayout)
        window.questionLayout.addWidget(tempWidget)
    for i in range(10):
        tempWidget = qtw.QWidget()
        tempLayout = qtw.QHBoxLayout()
        tempLayout.addWidget(qtw.QLabel(f'{i + 1})'))
        window.questions.append(qtw.QLabel(''))
        tempLayout.addWidget(window.questions[i + 10])
        tempLayout.addStretch(1)
        tempWidget.setLayout(tempLayout)
        window.questionLayout.addWidget(tempWidget)
    testContent.addStretch(3)
    testContent_.addLayout(window.questionLayout)
    testContent_.addStretch(1)
    window.optionLayout = qtw.QStackedLayout()
    window.options = list()
    for i in range(10):
        tempWidget = qtw.QWidget()
        tempLayout = qtw.QVBoxLayout()
        window.options.append(list())
        for j in range(4):
            currentOption = qtw.QHBoxLayout()
            currentOption.addWidget(qtw.QLabel(chr(65 + j)))
            window.options[i].append(qtw.QTextEdit())
            currentOption.addWidget(window.options[i][j])
            currentOption.addStretch(1)
            tempLayout.addLayout(currentOption)
        tempWidget.setLayout(tempLayout)
        window.optionLayout.addWidget(tempWidget)
    for i in range(10):
        tempWidget = qtw.QWidget()
        tempLayout = qtw.QVBoxLayout()
        window.options.append(list())
        for j in range(4):
            currentOption = qtw.QHBoxLayout()
            currentOption.addWidget(qtw.QLabel(chr(65 + j)))
            window.options[i + 10].append(qtw.QLabel(''))
            currentOption.addWidget(window.options[i + 10][j])
            currentOption.addStretch(1)
            tempLayout.addLayout(currentOption)
        tempWidget.setLayout(tempLayout)
        window.optionLayout.addWidget(tempWidget)
    testContent_.addLayout(window.optionLayout)
    _testContent_.addStretch(1)
    _testContent_.addLayout(testContent_)
    _testContent_.addStretch(3)
    testContent.addLayout(_testContent_)
    questionNavigator = qtw.QHBoxLayout()
    window.testPrev = qtw.QPushButton('previous')
    window.testNext = qtw.QPushButton('next')
    questionNavigator.addStretch(1)
    questionNavigator.addWidget(window.testPrev)
    questionNavigator.addStretch(4)
    questionNavigator.addWidget(window.testNext)
    questionNavigator.addStretch(2)
    testContent.addStretch(4)
    testContent.addLayout(questionNavigator)
    testLayout.addLayout(testContent)
    window.layout.addWidget(testWidget)
    
homepage = lambda window : window.layout.setCurrentIndex(0)

def student_login(window):
    window.login_error_text.hide()
    window.currentMode = False
    window.layout.setCurrentIndex(1)

def teacher_login(window):
    window.login_error_text.hide()
    window.currentMode = True
    window.layout.setCurrentIndex(1)

def refresh():
    credentials.append({'Developer' : 'password'})
    credentials.append({'Developer' : 'password'})
    topics.append('Stars and Galaxies')
    topics.append('topic 2')

def login_submit(user_id_obj, password_obj, window):
    user_id = user_id_obj.text()
    password = password_obj.text()
    if user_id in credentials[window.currentMode]:
        if password == credentials[window.currentMode][user_id]:
            user_id_obj.setText('')
            password_obj.setText('')
            window.userID = user_id
            window.password = password
            loggedInPage(window)
        else:
            password_obj.setText('')
            window.login_error_text.setText('Invalid Password')
            window.login_error_text.show()
    else:
        user_id_obj.setText('')
        password_obj.setText('')
        window.login_error_text.setText('Invalid user ID')
        window.login_error_text.show()

def create_new_user(window):
    window.userReturn.clicked.disconnect()
    if window.currentMode:
        window.teacherCodeWidget.show()
        window.userReturn.clicked.connect(partial(teacher_login, window))
    else:
        window.teacherCodeWidget.hide()
        window.userReturn.clicked.connect(partial(student_login, window))
    window.text1.setText('Enter Username:  ')
    window.text2.setText('Enter Password:  ')
    window.text3.setText('Confirm Password:')
    window.layout.setCurrentIndex(2)

def loggedInPage(window):
    window.hello.setText('Hello ' + window.userID + '!')
    window.existingTest.clear()
    window.existingTest.addItems(topics)
    if window.currentMode:
        window.loggedTeacher.show()
        window.testLabel.setText('Alter test')
    else:
        window.loggedTeacher.hide()
        window.testLabel.setText('Take test')
    window.layout.setCurrentIndex(3)

def makeTest(window):
    for i in range(10):
        window.questions[i].setPlainText('')
        for j in range(4):
            window.options[i][j].setPlainText('')
    readyPage(0)
    window.layout.setCurrentIndex(4)

def readyPage(pageNo):
    mode = pageNo // 10
    pageNo %= 10
    if pageNo == 0:pass

credentials = list()
topics = list()
refresh()
app = qtw.QApplication([])
window = MainWindow()
window.show()
app.exec()
